name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to create (e.g. v1.0.0)'
        required: true
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Creates tag for release
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin
          git tag -f ${{ env.RELEASE_TAG }}
          git push -f origin ${{ env.RELEASE_TAG }}
      - name: Publish container image
        run: |
          docker login -u ${{ secrets.DOCKER_CREDENTIALS_USERNAME }} -p ${{ secrets.DOCKER_CREDENTIALS_PASSWORD }}
          docker build -t ${{ vars.DOCKER_NAMESPACE }}/duice-example:${{ env.RELEASE_TAG }} -t ${{ vars.DOCKER_NAMESPACE }}/duice-example:latest .
          docker push ${{ vars.DOCKER_NAMESPACE }}/duice-example:${{ env.RELEASE_TAG }}
          docker push ${{ vars.DOCKER_NAMESPACE }}/duice-example:latest
